- hosts: all
  remote_user: vagrant
  become: yes
  become_method: sudo
  vars_files:
    - /vagrant/provision/ansible/default.yml
    - /vagrant/vm.yml
  roles:
    - { role: common }
    - { role: git,        when: PROVISION.git == 1 }
    - { role: ssh }
    - { role: docker,     when: PROVISION.docker == 1 }
    - { role: disk  }
    - { role: dnsmasq }
    - { role: motd }
  #   - { role: docker-proxy, when: PROVISION.dockerProxy == 1 }
  #   - { role: mail,         when: PROVISION.mail == 1 }
    - { role: ntp }
  #   - { role: firewall       }
    - { role: php ,       when: PROVISION.clitools == 1 }
    - { role: clitools ,  when: PROVISION.clitools == 1 }
  #   - { role: monit          }
    - { role: user  }
    - { role: customization }
    - { role: finalize }
