- hosts: all
  remote_user: vagrant
  become: yes
  become_method: sudo
  vars_files:
    - /vagrant/provision/ansible/default.yml
    - /vagrant/vm.yml
  roles:
    - common
    - git
    - ssh
    - docker
    - disk 
    - dnsmasq
    - motd
  #   - { role: docker-proxy, when: PROVISION.dockerProxy == 1 }
  #   - { role: mail,         when: PROVISION.mail == 1 }
    - ntp
  #   - { role: firewall       }
    - clitools
  #   - { role: monit          }
    - user 
    - customization
    - finalize
