- name: Set shell
  command: 'chsh -s "{{ PROFILE.shell }}" vagrant'
  when: PROFILE.shell is defined

- name: Set bash/zsh file perms
  file:
    path: '{{ item.path }}'
    owner: vagrant
    group: vagrant
    mode:  0644
  with_items:
   - { path: '/home/vagrant/.zshrc' }
   - { path: '/home/vagrant/.zshrc.local' }
   - { path: '/home/vagrant/.bashrc' }
  ignore_errors: True