- name: Restart postfix
  command: '{{ item }}'
  with_items:
    - postmap /etc/postfix/recipient_canonical_maps
    - postmap /etc/postfix/additional_headers
    - service postfix restart

- local_action: mail
                host='127.0.0.1'
                port=25
                subject="Welcome to DEVELOPMENT-VM"
                body="This is just a testmail :-)"
                from="vagrant@localhost (DEVELOPMENT-VM)"
                to="vagrant@localhost"
                charset=utf8
