- name: Fetch zshrc
  command: 'wget {{ item.remote }} -O {{ item.path }}'
  with_items:
   - { remote: 'http://git.grml.org/f/grml-etc-core/etc/zsh/zshrc', path: '/home/vagrant/.zshrc' }
  args:
    creates: '/home/vagrant/.zshrc'

- name: Fetch zshrc.local
  command: 'wget {{ item.remote }} -O {{ item.path }}'
  with_items:
   - { remote: 'http://git.grml.org/f/grml-etc-core/etc/skel/.zshrc', path: '/home/vagrant/.zshrc.local' }
  args:
    creates: '/home/vagrant/.zshrc.local'