- name: Install dnsmasq [Debian]
  apt:
    pkg:   '{{ item }}'
    state: present
  with_items:
    - dnsmasq
  when: ansible_os_family == 'Debian'

- name: Install dnsmasq [RedHat]
  yum:
    name:   '{{ item }}'
    state: present
  with_items:
    - dnsmasq
  when: ansible_os_family == 'RedHat'
