- name: Restart dovecot
  raw: '{{ item }}'
  with_items:
    - service dovecot restart

- name: Restart postfix
  command: '{{ item }}'
  with_items:
    - postmap /etc/postfix/recipient_canonical_maps
    - postmap /etc/postfix/additional_headers
    - service postfix restart
